### ISSUE TITLE
Game Crash im Store

### ISSUE THREAD

**Issue by matze0301** [VertexDezign/ParkVehicle#20]
Hi,

erstmal Danke fuer den Mod, den ich sehr gerne verwende.

Allerdings gibt es bei mir einen kompletten Crash des Spiels, und es muss hart beendet werden.

Vorgehen:

- Neues Savegame, ausschliesslich Park Vehicle als Mod, Riverbend Springs Map
- Nach dem ersten Start in den Store gehen, z.B. gleich den ersten kleinen Traktor nehmen und im Kaufmenue eine der Optionen (z.B. Reifen) **schnell** durchwechseln.
- Man kann zwar normalerweise noch den Store beenden, doch zurueck auf der Map geht gar nichts mehr.

Log anbei.
[Park-Vehicle-Crash-log.txt](https://github.com/user-attachments/files/18240272/Park-Vehicle-Crash-log.txt)

PS: Was passiert wenn man den Traktorkauf verlaesst und ein anderes Fahrzeug kaufen will, sieht man auf dem Screenshot ;-)
![fsScreen_2024_12_24_15_21_23](https://github.com/user-attachments/assets/6611b82f-d1a3-4609-98a5-294ac9b4cc67)

Lustigerweise hatte CP ein ganz aehnliches Problem, vielleicht hilft deren Loesung Dir? Hier die Issue dazu:
https://github.com/Courseplay/Courseplay_FS25/issues/62

**Comment by Grisu118** [comment]
Interessant, mir war es bisher nicht möglich das zu reproduzieren. Ich muss mir das von Courseplay noch genauer anschauen, aber zumindest aktuell weiss ich nicht was da falsch läuft. 🤔

**Comment by Grisu118** [comment]
Kannst du mir einmal sagen was bei dir auf Zeile 149 in der `ParkVehicle.lua` steht?. Die Zeilennummer passt eigentlich überhaupt nicht.

**Comment by matze0301** [comment]
Es sieht so aus, als haette ich nen falschen Alarm ausgeloest.
Mein Mod heisst "FS25_park_vehicle.zip", wenn ich das Archiv aber oeffne, sind alle Timestamps von 2022
Es handelt sich also offensichtlich um die FS22er Version.
Das haette mir auch auffallen koennen, denn im Log steht das hier:

"Available mod: (Hash: faf61c217fe328c90b266cff061e002f) (Version: 1.1.0.0) FS25_park_vehicle"

aber die 25er Version hat nur Version 1.0.0.0

Ich kann nachvollziehen, dass ich den Mod Ende November heruntergeladen habe, aber nicht mehr, von wo.

Also sorry fuer die Noise, scheint sich geklaert zu haben.

**Comment by Grisu118** [comment]
Ah, sehr gut. Probleme die sich von selbst lösen mag ich am liebsten :)
