### ISSUE TITLE
[FEATURE REQUEST] Quick shortcut to unpark all vehicles

### ISSUE THREAD

**Issue by MicaelJarniac** [VertexDezign/ParkVehicle#8]
I've been using this mod and it really helps with making it quicker to get to important vehicles, but one problem I've had is that it's hard to keep track of which vehicles are currently parked, and finding them to unpark.

The feature I'm suggesting is to have a shortcut (either a different key or holding the current parking mode key pressed for like 2 seconds) that unparks all vehicles, so we can then quickly switch between all the vehicles again.

Having this as a secondary action on the same key used for parking (holding down) would be ideal IMO, so we don't have to worry about configuring two keys.

Thanks for the mod!

**Comment by Grisu118** [comment]
I like the idea, will take a look into into it
