### ISSUE TITLE
Mod doesn't work with the latest patch and precision dlc

### ISSUE THREAD

**Issue by mrdppd** [VertexDezign/ParkVehicle#9]
went to park combine for winter as usual and didn't saw icon in a usual place. Tried to find keybind in settings - nothing. Tried updating moddesc version - didn't help

**Comment by jason0611** [comment]
Hi, 
ParkVehicle is working fine here with Precision Farming enabled and latest patch installed.
Are you using the ChangedMotorSound-Script (FS19_changedMotorSound)? There is a known issue with it regarding ParkVehicle (and other mods). See also https://www.lsfarming-mods.com/wbb/thread/3001-changed-motor-sounds-script-1-0-0-1/?postID=30377#post30377.
Regards, 
Martin

**Comment by mrdppd** [comment]
Thank you very much!

**Comment by Grisu118** [comment]
Thanks for the info, can look into it next month hopefully. As I already have the plan to use the changed motor sound script in my savegame. 

But first I need to move to my new Apartment and resetup fs on my new computer

**Comment by jason0611** [comment]
I've made some investigations: FS19_changedMotorSounds overwrites the function Util.getFilename and redirects the path of modDesc.xml to it's own directory. I've replaced the function-call by using g_currentModDirectory to create the path.
